services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: my_wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./mappings/:/home/wiremock/mappings
      - ./files/:/home/wiremock/__files
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
